version: '3.8'

services:
  eventura-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eventura-app
    restart: unless-stopped
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTPS_PORT=5002
    volumes:
      - ~/.aspnet/https:/https:ro
      - eventura_data:/app/data
    networks:
      - eventura-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  # PostgreSQL database (for production)
  eventura-db:
    image: postgres:16-alpine
    container_name: eventura-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eventura
      POSTGRES_USER: eventura_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
      POSTGRES_INITDB_ARGS: "--auth-local=password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - eventura-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventura_user -d eventura"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true

  # Redis cache (for session storage)
  eventura-redis:
    image: redis:7-alpine
    container_name: eventura-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password}
    volumes:
      - redis_data:/data
    networks:
      - eventura-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true

networks:
  eventura-network:
    driver: bridge
    name: eventura-network

volumes:
  eventura_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local